# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yCieOimj7Ltu-5Q8P036rylB1sEpa7qy
"""

a=30
b=20
a+b

-b

a-b

a*b

a/b

a=13
b=11
a/b

a//b

"""operators

"""

#variables
a=10
b=4

# addition
print("addition:",a+b)

#substraction
print("substraction:",a-b)

#multiplication
print("multiplication:",a*b)

#division
print("division:",a/b)

distance=7425
speed=550
time=distance/speed
print(time)

x=50
tip=x*20/100
print(tip)

x=50
tip=x*40/100
print(tip)

x=125
tip=x*20/100
print(tip)

x=204.8
tip=x*20/100
print(tip)

x=1024
tip=x*20/100
print(tip)



a=10
b=20
print(a>b)
print(a<b)
print(a==b)
print(a!=b)
print(a>=b)
print(a<=b)

a=True
b=False
print(a and b)
print(a or b)
print(not a)

a=10
b=a
print(b)
b+=a
print(b)
b-=a
print(b)
b*=a
print(b)
b<<=a
print(b)

a=10
b=20
c=a

print(a is not b)
print(a is c)
print(b is c)

x=10
y=15
list=[10,20,30,40,50]

if("x not in list"):
  print("x is NOT present in given list")
else:
  print("x is present in the list")

if(y in list):
  print("y is present in the list")
else:
  print("y is not present in the list")

(1,2,3)+(4,5,6)



[1,2,3]+[4,5,6]

"hello"+""+"world"

(1,2,3)*3

age=16
if age<18:
  print("you can't vote!")
else:
  print("you can vote!")
print("done!")

age=20
print("you can't vote!") if age< 18 else print("you can vote!")
print("done!")

"""# New Section

# New Section
"""



age=int(input("enter your age:"))
if age>=18:
  print("you are eligible for vote")
else:
    print("you are not eligible for vote")
    print("done!")

if 5>1:
  print("thats true!")

x=35

if x>20:
  print("above twenty,")
  if x>30:
    print("and also above 30!")

a=33
b=33
if b>a:
  print("b is greater than a ")
elif a==b:
    print("a and b are equal")

a=200
b=33
if b>a:
  print("b is greater than a")
elif a==b:
  print("a and b are equal")
else:
  print("a is greater than b")

a=2
b=220
print("A") if a>b else print("B")

a=200
b=30
if a>b: print("a is greater than b")

num = int(input("enter a number:"))
if num % 2 == 0:
  print("even number")
else:
  print("odd number")

weight=int(input("enter weight"))
height=float(input("enter height"))
if weight < 18.5:
  print ("underweight")
if x>=18.5 and x<25:
    print("normal")
if x>=25 and x<30:
  print('over weight')
if x>=30:
  print('obesity')

weight=int(input("enter weight"))
height=float(input("enter height"))
if weight < 18.5:
  print ("underweight")
elif x>=18.5 and x<25:
    print("normal")
elif x>=25 and x<30:
  print('over weight')
elif x>=30:
  print('obesity')

